version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    #volumes:
   # - ./var/lib/api:/app
   #   - ./home/david/git/proba/docker-crash-course/app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
  #  stdin_open: true
 # volumes:
  #  - ./home/david/git/proba/docker-crash-course/api:/app
   #   - ./home/david/git/proba/docker-crash-course/app/node_modules